### ISSUE TITLE
multiple directives

### ISSUE THREAD

**Issue by kwatog** [excaliburhan/vue-hammerjs#1]
I might be doing it wrong but can we actually have multiple directives on same element?
For example, I want to catch panstar, panmove, and panend on the same element. 

`<div v-hm:panstart="onPanStart" v-hm:panmove="onPanMove" v-hm:panend="onPanEnd">`

only one is triggered.

**Comment by excaliburhan** [comment]
> I might be doing it wrong but can we actually have multiple directives on same element?
> For example, I want to catch panstar, panmove, and panend on the same element.
> 
> `<div v-hm:panstart="onPanStart" v-hm:panmove="onPanMove" v-hm:panend="onPanEnd">`
> 
> only one is triggered.

you can only have one v-hm directive
